# Setup
title:        "Newen"
tagline:      "Linguagens e Tecnologia"
baseurl:      ""
paginate:     1
locale:       "pt"

# About/contact
author:
  name:       Newen Tecnologia
  url:        http://tec.newen.pub 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
